# -*- coding: utf-8 -*-
"""app

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xa5RwMPLIVEmdPgoJGlgnZwf89y9lYdd
"""

import gradio as gr

def interact_function(user_question):
    # Your user_input logic here
    embeddings = GoogleGenerativeAIEmbeddings(model="models/embedding-001")

    new_db = FAISS.load_local("faiss_index", embeddings)

    docs = new_db.similarity_search(user_question)

    chain = get_conversational_chain()

    response = None
    try:
      response = chain({"input_documents": docs, "question": user_question}, return_only_outputs=True)
      print(response
)
      # st.write("Reply: ", response["output_text"])
    except Exception as e:
      logging.error(f"Error in user_input: {str(e)}")
      # Handle the error appropriately.

      print(docs)

      st.write("Reply: ", response["output_text"])
    return response

iface = gr.Interface(fn=interact_function, inputs="text", outputs="text")
iface.launch()